name: Fetch crypto bot logs every week
on:
  schedule:
    - cron: '0 0 * * 1'  # This will run the workflow every Monday at midnight
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CLOUD_STORAGE }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Fetch data from Google Cloud Storage
      run: gsutil cp gs://free-tier-driftbot/SOL_history.csv ./files/SOL_history.csv
