name: Fetch crypto bot logs every week
on:
  schedule:
    - cron: '15 * * * 1'
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_VM }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Fetch data from Google Cloud Storage
      run: gsutil cp gs://crypto-bot-logs/SOL_history.csv ./files/SOL_history.csv

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email github-actions[bot]@users.noreply.github.com
        git add ./files/SOL_history.csv
        git commit -m "Fetch latest project performance data"
        git push
